import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Your IT Experts | ITI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full">
        <h1>Hello World</h1>
      </div>
      <div className="h-screen">
        <h1>Hello World</h1>
      </div>
      <div className="h-screen">
        <h1>Hello World</h1>
      </div>
    </>
  );
};

export default Home;
